### ISSUE TITLE
Disabled threading by default

### ISSUE THREAD

**Issue by lsgd** [digmore/docker-django-uwsgi#1]
I wondered whether you want to add `enable-threads =  True` to your default uwsgi.ini.

> By default the Python plugin does not initialize the GIL. This means your app-generated threads will not run. If you need threads, remember to enable them with enable-threads

Source: http://uwsgi-docs.readthedocs.org/en/latest/ThingsToKnow.html?highlight=enable-threads

**Comment by digmore** [comment]
Thanks @lukas-schulze for sharing the tip. I've added it to my build.
